package docs

import (
	"strings"
	"testing"
)

func TestNormalizeSourceLinks_StripsLineAnchors(t *testing.T) {
	cases := []struct {
		in   string
		want string
	}{
		{
			in:   "See [type Client](https://github.com/QoderAI/qoder-cloud-agents-sdk-go/blob/main/forward/client.go#L14) for details.",
			want: "See [type Client](https://github.com/QoderAI/qoder-cloud-agents-sdk-go/blob/main/forward/client.go) for details.",
		},
		{
			in:   "Range link https://github.com/QoderAI/qoder-cloud-agents-sdk-go/blob/main/forward/batch.go#L100-L164 here",
			want: "Range link https://github.com/QoderAI/qoder-cloud-agents-sdk-go/blob/main/forward/batch.go here",
		},
		{
			in:   "No anchor: https://github.com/QoderAI/qoder-cloud-agents-sdk-go/blob/main/managed/client.go stays.",
			want: "No anchor: https://github.com/QoderAI/qoder-cloud-agents-sdk-go/blob/main/managed/client.go stays.",
		},
		{
			in:   "External link https://github.com/other/repo/blob/abc123/file.go#L10 untouched.",
			want: "External link https://github.com/other/repo/blob/abc123/file.go#L10 untouched.",
		},
	}
	for _, c := range cases {
		got := normalizeSourceLinks(c.in)
		if got != c.want {
			t.Errorf("normalizeSourceLinks:\n  in:   %q\n  want: %q\n  got:  %q", c.in, c.want, got)
		}
	}
}

func TestNormalizeSourceLinks_FailsOnSHAInRepoLink(t *testing.T) {
	// If gomarkdoc ever emits a SHA-based ref for this repo, callers should
	// detect it via the post-check; normalizeSourceLinks itself only strips
	// line anchors — assert the URL passes through untouched so the check
	// stage can surface it as unnormalized.
	in := "https://github.com/QoderAI/qoder-cloud-agents-sdk-go/blob/abcdef1234567890/forward/client.go"
	if got := normalizeSourceLinks(in); got != in {
		t.Errorf("SHA-ref link should be untouched by normalizer: got %q", got)
	}
}

func TestStripNonDeterministic_NoOpOnCleanInput(t *testing.T) {
	// Determinism was empirically confirmed in the spike; this test guards
	// against future post-processing accidentally mutating clean gomarkdoc
	// output.
	in := "<!-- Code generated by gomarkdoc. DO NOT EDIT -->\n\n# forward\n\nGenerated by [gomarkdoc](<https://github.com/princjef/gomarkdoc>)\n"
	got := stripNonDeterministic(in)
	if !strings.Contains(got, "# forward") {
		t.Errorf("stripNonDeterministic dropped legitimate content: %q", got)
	}
}
