package forward

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/QoderAI/qoder-cloud-agents-sdk-go/convention"
	"github.com/QoderAI/qoder-cloud-agents-sdk-go/convention/apijson"
	"github.com/QoderAI/qoder-cloud-agents-sdk-go/convention/apiquery"
	"github.com/QoderAI/qoder-cloud-agents-sdk-go/convention/option"
	"github.com/QoderAI/qoder-cloud-agents-sdk-go/convention/param"
	"github.com/QoderAI/qoder-cloud-agents-sdk-go/convention/respjson"
)

// ChannelQRSessionService provides Forward ChannelQRSession operations.
type ChannelQRSessionService struct {
	Options []option.RequestOption
}

func NewChannelQRSessionService(opts ...option.RequestOption) ChannelQRSessionService {
	return ChannelQRSessionService{Options: slices.Clone(opts)}
}

// Create Channel QR Session
func (r *ChannelQRSessionService) New(ctx context.Context, channelID string, params ChannelQRSessionNewParams, opts ...option.RequestOption) (res *ChannelQRSession, err error) {
	if channelID == "" {
		return nil, fmt.Errorf("missing required channel_id parameter")
	}
	if params.IdempotencyKey.Valid() {
		opts = append([]option.RequestOption{option.WithHeader("Idempotency-Key", fmt.Sprint(params.IdempotencyKey.Value))}, opts...)
	}
	opts = slices.Concat(r.Options, opts)
	path := fmt.Sprintf("channels/%s/qr_sessions", url.PathEscape(channelID))
	err = convention.ExecuteNewRequest(ctx, http.MethodPost, path, nil, &res, opts...)
	return res, err
}

type ChannelQRSessionNewParams struct {
	// Optional idempotency key for requests with side effects.
	IdempotencyKey param.Opt[string] `header:"Idempotency-Key,omitzero" json:"-"`
	paramObj
}

func (r ChannelQRSessionNewParams) URLQuery() (url.Values, error) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{ArrayFormat: apiquery.ArrayQueryFormatRepeat, NestedFormat: apiquery.NestedQueryFormatBrackets})
}

// Get Channel QR Session
func (r *ChannelQRSessionService) Get(ctx context.Context, sessionKey string, opts ...option.RequestOption) (res *ChannelQRSession, err error) {
	if sessionKey == "" {
		return nil, fmt.Errorf("missing required session_key parameter")
	}

	opts = slices.Concat(r.Options, opts)
	path := fmt.Sprintf("qr_sessions/%s", url.PathEscape(sessionKey))
	err = convention.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

type ChannelQRSession struct {
	// Opaque QR session key used to poll the status.
	SessionKey string `json:"session_key"`
	// ID of the associated Channel.
	ChannelID string `json:"channel_id"`
	// `wechat`, `feishu`, `dingtalk` or `wecom`.
	ChannelType string `json:"channel_type"`
	// Initial status, usually `waiting`.
	Status string `json:"status"`
	// Raw QR code content, usually a third-party authorization URL.
	QRCodeContent string `json:"qr_code_content"`
	// QR code image generated by the server.
	QRCodeImageBase64 string `json:"qr_code_image_base64"`
	// Expiration time.
	ExpiresAt string `json:"expires_at"`
	// null|Channel error code on failure.
	ErrCode string `json:"err_code"`
	// null|Channel error message on failure.
	ErrMsg string `json:"err_msg"`
	JSON   struct {
		SessionKey        respjson.Field
		ChannelID         respjson.Field
		ChannelType       respjson.Field
		Status            respjson.Field
		QRCodeContent     respjson.Field
		QRCodeImageBase64 respjson.Field
		ExpiresAt         respjson.Field
		ErrCode           respjson.Field
		ErrMsg            respjson.Field
		ExtraFields       map[string]respjson.Field
		raw               string
	} `json:"-"`
}

func (r ChannelQRSession) RawJSON() string                  { return r.JSON.raw }
func (r *ChannelQRSession) UnmarshalJSON(data []byte) error { return apijson.UnmarshalRoot(data, r) }
